"""empty message

Revision ID: 522e4f95ecce
Revises: b9e374fc33b8
Create Date: 2022-11-17 02:21:06.655705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522e4f95ecce'
down_revision = 'b9e374fc33b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('count', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies')
    # ### end Alembic commands ###
