"""empty message

Revision ID: 64da8db8ea03
Revises: ffe3d1ada394
Create Date: 2021-08-31 14:03:10.737173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64da8db8ea03'
down_revision = 'ffe3d1ada394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'new')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('new', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
