"""empty message

Revision ID: a30ab17c65f7
Revises: 64da8db8ea03
Create Date: 2021-08-31 14:04:15.584313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a30ab17c65f7'
down_revision = '64da8db8ea03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('image', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
