"""empty message

Revision ID: b9e374fc33b8
Revises: c806d9281e74
Create Date: 2022-11-17 01:52:09.471499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9e374fc33b8'
down_revision = 'c806d9281e74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sessionId', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phoneNumber', sa.String(), nullable=True),
    sa.Column('movie', sa.String(), nullable=True),
    sa.Column('movieConfirm', sa.String(), nullable=True),
    sa.Column('tlk', sa.Boolean(), nullable=True),
    sa.Column('probability', sa.String(), nullable=True),
    sa.Column('startDate', sa.String(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poll')
    # ### end Alembic commands ###
