"""empty message

Revision ID: c806d9281e74
Revises: f4928de90dc4
Create Date: 2022-08-27 13:12:44.865516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c806d9281e74'
down_revision = 'f4928de90dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('items', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'items')
    # ### end Alembic commands ###
