"""empty message

Revision ID: ffe3d1ada394
Revises: 66ce50019858
Create Date: 2021-08-31 14:02:09.992783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffe3d1ada394'
down_revision = '66ce50019858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('new', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'new')
    # ### end Alembic commands ###
